<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Library</OutputType>
    <RootNamespace>MomodoraRandomizer</RootNamespace>
    <AssemblyName>MomodoraRandomizer</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CustomFontDialog">
      <HintPath>References\CustomFontDialog.dll</HintPath>
    </Reference>
    <Reference Include="LiveSplit.Core">
      <HintPath>References\LiveSplit.Core.dll</HintPath>
    </Reference>
    <Reference Include="LiveSplit.Text">
      <HintPath>References\LiveSplit.Text.dll</HintPath>
    </Reference>
    <Reference Include="UpdateManager">
      <HintPath>References\UpdateManager.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
  <PropertyGroup>
    <PostBuildEvent>call $(MSBuildProjectDirectory)\postBuild.bat "MomodoraRandomizer.dll" "$(MSBuildProjectDirectory)\Components" "D:\7. Programas\Games\Livesplit\Components"</PostBuildEvent>
    <BaseOutputPath></BaseOutputPath>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
  </PropertyGroup>
</Project>